# 服务配置
server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.phoenix.ldemo.model
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
jwt:
  secret: my_secret_2020
  expiration: 1800